### PR TITLE
add CONTRIBUTORS file

### PR DESCRIPTION
**Pull request by zacchiro**

### CODE REVIEW

**Comment by tbm** [comment]
Is this useful? We have `docs/authors.md` already listing contributors? Do you think a `CONTRIBUTORS` (additionally) would be useful?

**Comment by zacchiro** [comment]
On Fri, Nov 13, 2020 at 04:03:33PM -0800, Martin Michlmayr wrote:
> Is this useful? We have `docs/authors.md` already listing
> contributors? Do you think a `CONTRIBUTORS` (additionally) would be
> useful?

I totally missed docs/authors.md :-) Just wanted to give more
visibility to external contributors, given we have a top-level AUTHORS
file. For that purpose, maybe AUTHORS can be turned into a symlink to
docs/authors.md and a new symlink CONTRIBUTORS could be added pointing
to the same file then?

**Comment by tbm** [comment]
I'm not sure what to do about this.  I guess I could split `docs/authors.md` into `docs/authors.md` and `docs/contributors` and do a symlink, but I'm not sure it's worth the hassle.

Is CONTRIBUTORS that common? And some call it CREDITS.  It seems it's not that of a standard (unlike e.g. LICENSE) that it seems worth the trouble but I don't know.

**Comment by zacchiro** [comment]
Just a couple of things:
- it's not a big issue, feel free to just close/ignore this
- my proposal is to not split anything, keep docs/authors.md as it is, turn AUTHORS into a symlink to it, and add another symlink to it called CONTRIBUTORS
I think it's a common convention, but I might be wrong, and I don't think it's worth checking one way or another :-)

**Comment by tbm** [comment]
I'll close for now, but maybe do something later.

**Pull request closed without merging**
