### PR TITLE
feat(dockerfile): initial commit of Dockerfile #239

### LINKED ISSUE #239: Dockerfile or image on Dockerhub?
Hi,

Is there a Dockerfile or existing image on Dockerhub?

I'm would like to run this on my Windows laptop.

If this doesn't exist, maybe I will try to create this.

### PR DESCRIPTION
**Pull request by dennislwm**
Run ledger2beancount from a Docker image. Fix #239.

To build the Docker image from Dockerfile:

`DOCKER_BUILDKIT=1 docker image build -t <IMAGENAME> .
`

To run ledger2beancount from the above image:

--- copy and paste into bash script ---
```
#-------------------------------------------------------------------------
# Usage:  docker run -rm -v <hostdir>:<containerdir>:rw <image> <FILE>
#   hostdir is the host directory that contains your ledger files
#   containerdir is an empty container directory for the app to read/write
#   image is the Docker image name
#   FILE is the ledger file name
if [ -z $1 ]; then
    echo "Run ledger2beancount from a Docker image"
    echo "Usage:"
    echo "  $0 <hostdir> <image> <FILE>"
    echo "  hostdir Use absolute path"
    exit
fi

docker run --rm -v $1:/usr/ledger2beancount/docker:rw $2 docker/$3
```
--- end ---

### CODE REVIEW

**Comment by tbm** [comment]
thank you.  Any reason you don't use `ubuntu:latest` btw?

**Comment by dennislwm** [comment]
> thank you. Any reason you don't use `ubuntu:latest` btw?

No reason, you can change to latest if you want.

**Review by tbm — APPROVED** [review]
Ok, I've now built an image from the Dockerfile.  Works fine.  Thank you!

**Comment by tbm** [comment]
> docker run --rm -v $1:/usr/ledger2beancount/docker:rw $2 docker/$3

It seems that `docker run --rm IMAGE` is enough to run.  Is there a reason not to do that?

**Comment by tbm** [comment]
I applied this manually.  Thank you!

**Comment by dennislwm** [comment]
-v $1:/usr/ledger2beancount/docker:rw 

mounts the host directory to docker container

This is because apps within the docker container cannot read or write to host files by default.

so that we can run read ledger files and write to beancount files outside the docker container.

**Comment by tbm** [comment]
Thanks again @dennislwm

**Pull request closed without merging**
